name: "Sandia Software Portal"
author: "Sandia Open Source <open-source@llnl.gov>"
title: Sandia Software Portal
description: "Sandia National Laboratory Software Portal"
remote_theme: LLNL/Jekyll-LLNL-Theme  # You might change this later.

url: "https://software.sandia.gov"
repo_url: "https://github.com/sandialabs/sandialabs.github.io"

# Google Analytics ID
# google_analytics:
#   tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
# twitter:
#   username: llnl_opensource

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: sandialabs/sandialabs.github.io
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
    - build
